FileVersion = 1
Projects = {Nanoforge = {Path = "."}, RfgTools = {Path = "Dependencies/RfgTools"}, "Beef.Linq" = {Path = "Dependencies/Beef.Linq/src"}, ImGui = {Path = "Dependencies/imgui-beef"}}
Unlocked = ["Zlib"]

[Workspace]
StartupProject = "Nanoforge"

[Configs.Debug.Win64]
Toolset = "LLVM"
BfSIMDSetting = "SSE4"

[Configs.Release.Win64]
BfSIMDSetting = "SSE4"

[Configs.Paranoid.Win64]
BfSIMDSetting = "SSE4"

[Configs.Test.Win64]
BfSIMDSetting = "SSE4"
